# Numpy Array operations


In [5]:
import numpy as np

#### Indexing and Slicing

In [7]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Basic Slicing", arr[2:7])
print("With Step", arr[1:8:2])
print("Negative indexing", arr[-3])

Basic Slicing [3 4 5 6 7]
With Step [2 4 6 8]
Negative indexing 8


In [11]:
arr_2d = np.array([[1,        2,         3],   # 0th row
                   [4,        5,         6],   # 1th row
                   [7,        8,         9]])  # 2th row
                # 0th Col  # 1th Col  # 2th Col

print("Specific element", arr_2d[1, 2])
print("Entire row: ", arr_2d[1])
print("Entire Column: ", arr_2d[:, 1])

Specific element 6
Entire row:  [4 5 6]
Entire Column:  [2 5 8]


#### Sorting

In [21]:
unsorted = np.array([2,4,6,5,3,8,9,1])
print("Sorted Array: ",np.sort(unsorted))

arr_2d_unsorted = np.array([[2,4,6],[1,3,5],[6,3,2]])
print("2D Sorted Array: ",np.sort( arr_2d_unsorted , axis=1 ))

Sorted Array:  [1 2 3 4 5 6 8 9]
2D Sorted Array:  [[2 4 6]
 [1 3 5]
 [2 3 6]]


#### Filter

In [33]:
number = np.array([1,2,3,4,5,6,7,8,9,10])
even_num = number[number % 2 == 0]
print("Even Numbers: ",even_num)

odd_num = number[number % 2 == 1]
print("Odd Numbers: ",odd_num)

Even Numbers:  [ 2  4  6  8 10]
Odd Numbers:  [1 3 5 7 9]


#### Filter with mask

In [62]:
mask = number * 2
print("Square: ",mask)

Square:  [ 2  4  6  8 10 12 14 16 18 20]


#### Fancy indexing vs np.where()

In [75]:
indices = np.array([0,2,4])
print(number[indices])

where_result = np.where(number > 5)
print(where_result)
print("NP where", number[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9], dtype=int64),)
NP where [ 6  7  8  9 10]


In [79]:
condition_array = np.where(number>5, "True" , "False")
print(condition_array)

['False' 'False' 'False' 'False' 'False' 'True' 'True' 'True' 'True'
 'True']


#### Adding and removing data

In [89]:
a = np.array([1,2,3])
b = np.array([4,5,6])

# Wrong Way to add the list...
# added = a + b
# print(added)

added = np.concatenate((a,b))
print(added)

[1 2 3 4 5 6]


#### array compatibilty

In [92]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6, 7])
c = np.array([7, 8, 9])

print("Compatibility shapes", a.shape == b.shape)

Compatibility shapes False


#### Adding Row and Column using vstack and hstack respectively

In [101]:
original = np.array([[1, 2], [3, 4]])
new_row = np.array([5,6])
new_column = np.array([[7],[8]])

new_row_added = np.vstack((original , new_row))
print("The array with row added: \n",new_row_added)

new_column_added = np.hstack((original , new_column))
print("The array with column added: \n",new_column_added)

The array with row added: 
 [[1 2]
 [3 4]
 [5 6]]
The array with column added: 
 [[1 2 7]
 [3 4 8]]


#### Delete Opeartion

In [106]:
arr = np.array([2,4,5,6])
deleted = np.delete(arr ,2)
print(deleted)

[2 4 6]
